version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: job-tracker-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - job-tracker-network

  # Express API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: job-tracker-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/jobtracker
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - job-tracker-network
    volumes:
      - ./server/uploads:/app/uploads

  # React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: job-tracker-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - job-tracker-network

volumes:
  mongodb_data:
    driver: local

networks:
  job-tracker-network:
    driver: bridge



